"""change value type

Revision ID: 00e276941bfe
Revises: 85cc09738213
Create Date: 2019-07-20 19:23:53.425552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e276941bfe'
down_revision = '85cc09738213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_score_value'), 'score', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_value'), table_name='score')
    # ### end Alembic commands ###
