"""users table

Revision ID: 85cc09738213
Revises: 
Create Date: 2019-07-20 17:33:46.006341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cc09738213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_username', sa.String(length=64), nullable=True),
    sa.Column('slack_userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_slack_userid'), 'user', ['slack_userid'], unique=True)
    op.create_index(op.f('ix_user_slack_username'), 'user', ['slack_username'], unique=True)
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orig_input', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_timestamp'), 'score', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_timestamp'), table_name='score')
    op.drop_table('score')
    op.drop_index(op.f('ix_user_slack_username'), table_name='user')
    op.drop_index(op.f('ix_user_slack_userid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
